
Number_of_hardware: 3

Service:
    #マイクロサービスのレプリカ数とハードウェアマッピング
  - service_id: test_service
    microservices:
      service1: 1
      service2: 1
      service3: 1

    hardware_map: 
      service1: 
        1: 0
      service2:
        1: 1
      service3:
        1: 2

    jobs_of_service:
        service1:
            - job1
        service2:
            - job2
        service3:
            - job3
    #A->B->Cの順で構成される簡単なくえり
    #job1の情報が基本になる予定
    query:
      - query_name: query1
        start_nodes:
          - job1
        number_of_job: 3
    jobs: 
      job1:
        microservice: service1
        jobname: job1
        remain_time: 10
        number_of_next_jobs: 1
        next_jobs:
            - servicename: service2
              jobname: job2
              relation: until
      job2:
        microservice: service2
        jobname: job2
        remain_time: 5
        number_of_next_jobs: 1
        next_jobs:
            - servicename: service3
              jobname: job3
              relation: until
      job3:
        microservice: service3
        jobname: job3
        remain_time: 15
        number_of_next_jobs: 0
        next_jobs:
            - 
